
-- Create a table to store department information in the hospital
CREATE TABLE Department ( 
    DeptID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- automaticallu assign a unique primary key to identifier each department
    DepatName       VARCHAR (250) NOT NULL,                                 -- department name, attribute must be filled
    LocationName    VARCHAR (250) NOT NULL                                  -- location within the building such as floor number. The attribute must be filled
)

-- Create a table to store doctor information in the respective department
CREATE TABLE Doctor (
    DoctorID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- assign a unique primary key to identify each new dotor automatically 
    FullName    VARCHAR (100) NOT NULL,                                     -- to store doctor name, must be filed
    Specialty   VARCHAR (250) NOT NULL,                                     -- to store doctor's specialty field, must be filled
    DeptID      NUMBER NOT NULL,                                            -- referencing a department ID from department table, must be filled
    Phone       NUMBER(9),                                                  -- to store phone number, maximum of 10 digits including first zero
    Email       VARCHAR(100)  UNIQUE,                                       -- to store email of the doctor
    CONSTRAINT FK_Doctor_Department                                         -- define a foerign key constraint for integrity
        FOREIGN KEY (DeptID) REFERENCES Department (DeptID)                 -- ensure that the key is already present in the department table
);


-- Create a table to allow registering patient in the hospital registry database
CREATE TABLE Patient (
    PatientID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                -- assign a unique primary identifier to each new patient automatically
    FullName    VARCHAR (100) NOT NULL,                                             -- patient name, must be filled
    GENDER      VARCHAR (8) CHECK (Gender IN ('Male','Female')),                    -- patient gender, expected Male or Female only
    DOB         DATE DEFAULT SYSDATE NOT NULL,                                      -- date of birth, must be filled
    Contact     NUMBER (9) NOT NULL,                                                -- contact detail number, a maximum of 10 digits including first zero and must be filled
    Address     VARCHAR (250)                                                       -- location of the patient e.g. country or district
);

-- create a table to store new appointments that links a patient and doctor
CREATE TABLE Appointment(
    AppointmentID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,            -- assign a unique primary identifier to each appointment automatically
    PatientID       NUMBER NOT NULL,                                                -- define a referenced key (patient id) which must first be already present in the patient table
    DoctorID        NUMBER NOT NULL,                                                -- define a referenced key (patient id) which must first be already present in the doctor table
    VisitDate       DATE DEFAULT SYSDATE NOT NULL,                                  -- define a date the patient visisted a doctor, must be filled
    Diagnosis       VARCHAR (500) NOT NULL,                                         -- doctor's diagnosis of the patient's health conditions, must be filled
    Status          VARCHAR (250) CHECK (Status IN ('completed', 'pending')),       -- only accepte completed or pending keywords which will be updated accordingly
    
    -- define corresponding foreign keys
    CONSTRAINT FK_Appointment_Doctor                                               
        FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID),                         -- define foreign key (doctor id ) which must first be already present in the doctor table
    CONSTRAINT FK_Appointmet_Patient
        FOREIGN KEY (PatientID) REFERENCES Patient(PatientID)                       -- define foreign key (patient id) which must first be already present in the doctor table
);


-- create a table to store new prescriptions
CREATE TABLE Prescription (
    PrescriptionID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- assign unique primary identifier to new prescription for the appointment 
    AppointmentID       NUMBER NOT NULL,                                            -- define referenced key (appointment id) for the appointment which must first be already present in the appointment table
    Notes               VARCHAR (500),                                              -- doctor notes during consultation with the patient
    DateIssued          DATE DEFAULT SYSDATE NOT NULL,                              -- date when the consultation took place must be filled
    CONSTRAINT FK_Prescription_Appointment                                          -- define the foreing key constraint for integrity
        FOREIGN KEY (AppointmentID) REFERENCES Appointment(AppointmentID)           -- the key must be already present in the appointment table
        ON DELETE CASCADE                                                           -- the record cannot first be deleted in this table as long as it is present in the appointment table (parent)
);
select * from prescription;

delete from prescription where appointmentid = '2'; 













-- Create a table to store medication for the appointment
CREATE TABLE Medication (
    MedID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,            -- automatically assign a unque primary medication identifier in the database for stocking
    PrescriptionID      NUMBER NOT NULL,                                                -- define referenced key for each prescription which must first be already present in the prescription table
    DrugName            VARCHAR (200) NOT NULL,                                         -- prescribed drug, must be filled
    Dosage              VARCHAR (500) NOT NULL,                                         -- define dosage, must be filled
    DurationN           VARCHAR (150) NOT NULL,                                         -- time to finish the dosage, must be filled
    Quantity            VARCHAR (150) NOT NULL,                                         -- quantity of each medication prescribed, must be filled
    CONSTRAINT FK_Medication_Prescription                                               -- define foreign key constraint for integrity
        FOREIGN KEY (PrescriptionID) REFERENCES Prescription (PrescriptionID)           -- the key must first be already present in the prescription table
        ON DELETE CASCADE                                                               -- the record cannot first be deleted in this table as long as it is present in the appointment table (parent)
);

-- select * from tab;


-- A log table to record new prescription transactions
CREATE TABLE Prescription_Log (                                                 -- automatically create new prescription log table to store logs whenever new prescription is created
    LogID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- assign unique log id to each new log, must be filled
    PrescriptionID  NUMBER NOT NULL,                                            -- define corresponding prescription id , must be filled
    AppointmentID   NUMBER NOT NULL,                                            -- define corresponding appointment id for each new prescription, must be filled
    LogMessage      VARCHAR(500),                                               -- define log message holder
    LogDate         DATE DEFAULT SYSDATE NOT NULL                               -- define log date for tracing possibly the time series of events, must be filled
);



-- A trigger to prevent updating prescription notes for incomplete appointments
CREATE OR REPLACE TRIGGER trg_prescription_notes_update                             -- define trigger name
BEFORE UPDATE OF Notes ON Prescription                                              -- Trigger fires before updating the 'Notes' column in Prescription table
FOR EACH ROW                                                                        -- Row-level trigger: fires for each updated prescription record
DECLARE
    v_status Appointment.Status%TYPE;                                               -- Declare a variable to hold the status of the related appointment
BEGIN
    SELECT Status                                                                   -- Get the status of the related appointment
    INTO v_status                                                                   -- Store the appointment status into the variable
    FROM Appointment
    WHERE AppointmentID = :NEW.AppointmentID;                                       -- Match the appointment corresponding to the prescription being updated


    -- Check if the appointment is completed
    IF v_status != 'completed' THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'Cannot update prescription notes: Appointment is not completed yet.');
    END IF;
END;


-- A trigger to log any new prescription being made with a date same as the one during prescription
CREATE OR REPLACE TRIGGER trg_prescription_insert_log                                   -- Creates or replaces a trigger for new prescriptions logs
AFTER INSERT ON Prescription                                                            -- after new prescription has been created
FOR EACH ROW                                                                            -- loop each newly created prescription
BEGIN                                                                                   -- start logging
    INSERT INTO Prescription_Log (PrescriptionID, AppointmentID, LogMessage, LogDate)   -- log into log table
    VALUES (
        :NEW.PrescriptionID,                                                            -- log the newly created prescription id
        :NEW.AppointmentID,                                                             -- log corresponding appointment
        'New prescription created for AppointmentID ' || :NEW.AppointmentID,            -- writr log message
        :NEW.DateIssued                                                                 -- uses the inserted prescription's date
    );
END;                                                                                    -- terminate logging if no new prescriptions exist






